services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    working_dir: /home/node/app/
    depends_on:
      - postgres
    environment:
      - DATABASE_URI=postgresql://postgres:mysecretpassword@postgres:5432/payload-db
      - PAYLOAD_SECRET=p4yl0ad_s3cr3t
      - GCS_BUCKET=stunting-cms-media
      - GCS_PROJECT_ID=stunting-cms

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=payload-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword

volumes:
  pgdata:
  node_modules:
